version: "3"

services:

  tinyproxy:
    image: dannydirect/tinyproxy:latest
    container_name: tinyproxy
    environment:
      - BASIC_AUTH_USER=user
      - BASIC_AUTH_PASSWORD=password
    ports:
      - 8888:8888
    command:
      - ANY
    tty: false

  finbourne-access-sdk-test:
    build: .
    container_name: finbourne-access-sdk-test
    image: finbourne/finbourne-access-sdk-test
    environment:
      - FBN_CLIENT_ID
      - FBN_CLIENT_SECRET
      - FBN_LUSID_ACCESS_URL
      - FBN_PASSWORD
      - FBN_TOKEN_URL
      - FBN_USERNAME
      - FBN_PROXY_ADDRESS=http://tinyproxy:8888
      - FBN_PROXY_USERNAME=user
      - FBN_PROXY_PASSWORD=password
    volumes:
      - .:/usr/src
    depends_on:
      - tinyproxy